### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by WangYong-Design** [sunghoonhong/SMAAC#2]
![image](https://user-images.githubusercontent.com/71626073/163505588-385eb86d-f5c0-4077-873e-339942518583.png)
Is this data the same  as the competition data?

**Comment by WangYong-Design** [comment]
And Is this code only available in on  WCCI grid2op==0.9.4?

**Comment by sunghoonhong** [comment]
Hi, WangYong-Design,

`'wcci' data` consist of a subset of train set provided in the competition, and a valid set provided in development phase of the competition, while a test set evaluated in the competition was not provided.
As the official version of grid2op used in competition is 0.9.1 and we developed in 0.9.4 (there were minor updates between them), we did our best to focus on the version and not sure if it supports newer versions.

**Comment by WangYong-Design** [comment]
Then how can i use all train set provided in the competition to train the agent?

**Comment by sunghoonhong** [comment]
You can use all train set originally provided by grid2op wcci data if you have json files containing several information of no-op policy (e.g., donothing_rewards), which can be generated manually.
